///|
pub extend MemoryRegion with Eq::{not_equal, equal}

///|
pub extend MemoryRegion with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CheckLevel with Eq::{not_equal, equal}

///|
pub extend CheckLevel with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LayoutRule with Eq::{not_equal, equal}

///|
pub extend LayoutRule with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LayoutIssue with Eq::{not_equal, equal}

///|
pub extend LayoutIssue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LayoutOptions with Eq::{not_equal, equal}

///|
pub extend LayoutOptions with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LayoutReport with Eq::{not_equal, equal}

///|
pub extend LayoutReport with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FlashOptions with Eq::{not_equal, equal}

///|
pub extend FlashOptions with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FlashPage with Eq::{not_equal, equal}

///|
pub extend FlashPage with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FlashPlan with Eq::{not_equal, equal}

///|
pub extend FlashPlan with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ReleaseRule with Eq::{not_equal, equal}

///|
pub extend ReleaseRule with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ReleaseIssue with Eq::{not_equal, equal}

///|
pub extend ReleaseIssue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CortexMReleaseOptions with Eq::{not_equal, equal}

///|
pub extend CortexMReleaseOptions with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CortexMReleaseReport with Eq::{not_equal, equal}

///|
pub extend CortexMReleaseReport with @moonbitlang/core/debug.Debug::{to_repr}
