///|
pub extend ImageChecksumAlgorithm with Eq::{not_equal, equal}

///|
pub extend ImageChecksumAlgorithm with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImageChecksum with Eq::{not_equal, equal}

///|
pub extend ImageChecksum with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MaskedPattern with Eq::{not_equal, equal}

///|
pub extend MaskedPattern with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AsciiSpan with Eq::{not_equal, equal}

///|
pub extend AsciiSpan with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ByteOrder with Eq::{not_equal, equal}

///|
pub extend ByteOrder with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CortexMVectorTable with Eq::{not_equal, equal}

///|
pub extend CortexMVectorTable with @moonbitlang/core/debug.Debug::{to_repr}
