///|
pub extend EntryPolicy with Eq::{not_equal, equal}

///|
pub extend EntryPolicy with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImageStatistics with Eq::{not_equal, equal}

///|
pub extend ImageStatistics with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FirmwareDiff with Eq::{not_equal, equal}

///|
pub extend FirmwareDiff with @moonbitlang/core/debug.Debug::{to_repr}
